name: unimate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.9.0
  provider: ^6.1.2
  http: ^1.2.0
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0
  file_picker: ^8.1.0
  image_picker: ^1.0.0
  pdfx: ^2.6.0
  path_provider: ^2.0.14
  open_file: ^3.2.1
  url_launcher: ^6.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
